name: Campus Parking - CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    # Remove or keep if you add backend job later
    # needs: build_backend  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Frontend
        run: |
          cd campus-parking/frontend/my-app
          npm install
          npm run build

      - name: Upload Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend_dist
          path: campus-parking/frontend/my-app/build