name: Deploy Flask Backend to Azure Web App

on:
  push:
    branches:
      - main  # or whichever branch you deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        working-directory: campus-parking/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare backend package for deployment
        working-directory: campus-parking/backend
        run: |
          zip -r backend.zip . -x "__pycache__/*" "*.pyc" "*.pyo" "venv/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: campus-parking-webapp    # your Azure App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: campus-parking/backend/backend.zip

      - name: Verify deployment
        run: |
          echo "Deployment completed! Visit your site at:"
          echo "https://campus-parking-webapp.azurewebsites.net"
