name: CI/CD — Build & deploy (Flask) to Azure Web App (Publish Profile)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          pytest -q || true

      - name: Zip app for deployment
        run: |
          # create a zip excluding git/CI files
          zip -r app.zip . -x ".git/*" ".github/*" "__pycache__/*" "*.pyc"

      - name: Deploy to Azure Web App (using publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: campus-parking-webapp            # change if your app name differs
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
