apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-parking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campus-parking-backend
  template:
    metadata:
      labels:
        app: campus-parking-backend
    spec:
      containers:
      - name: backend
        image: campus-parking-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: campus-parking-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
